# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  jobs_json:
    description: "Jenkins job name to build"
    required: true
outputs:
  build_url: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'