# action.yml
name: 'Jenkins trigget generation list'
description: 'Greet someone and record the time'
inputs:
  namespace:
    description: "Namespace"
    required: true
  # stage:
  #   description: "Jenkins job name to build"
  #   required: true
  jobs_path_string:
    description: "String of jobs path"
    required: true
outputs:
  jobs_string: # id of output
    description: 'Return all jobs'
runs:
  using: 'docker'
  image: 'Dockerfile'