# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  namespace:
    description: "Jenkins job name to build"
    required: true
  stage:
    description: "Jenkins job name to build"
    required: true
  jobs_path_string:
    description: "Jenkins job name to build"
    required: true
outputs:
  jobs_string: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'